[package]
name = "shortcut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive", "cargo"] }
kurbo = "0.9.0"
svg = "0.12.1"
